// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/academic/academic.proto

package academic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common "thaily/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============= Semester =============
type Semester struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Semester) Reset() {
	*x = Semester{}
	mi := &file_proto_academic_academic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Semester) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Semester) ProtoMessage() {}

func (x *Semester) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Semester.ProtoReflect.Descriptor instead.
func (*Semester) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{0}
}

func (x *Semester) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Semester) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Semester) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Semester) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Semester) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Semester) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type CreateSemesterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSemesterRequest) Reset() {
	*x = CreateSemesterRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSemesterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSemesterRequest) ProtoMessage() {}

func (x *CreateSemesterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSemesterRequest.ProtoReflect.Descriptor instead.
func (*CreateSemesterRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSemesterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSemesterRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateSemesterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semester      *Semester              `protobuf:"bytes,1,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSemesterResponse) Reset() {
	*x = CreateSemesterResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSemesterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSemesterResponse) ProtoMessage() {}

func (x *CreateSemesterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSemesterResponse.ProtoReflect.Descriptor instead.
func (*CreateSemesterResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSemesterResponse) GetSemester() *Semester {
	if x != nil {
		return x.Semester
	}
	return nil
}

type GetSemesterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSemesterRequest) Reset() {
	*x = GetSemesterRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSemesterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemesterRequest) ProtoMessage() {}

func (x *GetSemesterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemesterRequest.ProtoReflect.Descriptor instead.
func (*GetSemesterRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{3}
}

func (x *GetSemesterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSemesterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semester      *Semester              `protobuf:"bytes,1,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSemesterResponse) Reset() {
	*x = GetSemesterResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSemesterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemesterResponse) ProtoMessage() {}

func (x *GetSemesterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemesterResponse.ProtoReflect.Descriptor instead.
func (*GetSemesterResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{4}
}

func (x *GetSemesterResponse) GetSemester() *Semester {
	if x != nil {
		return x.Semester
	}
	return nil
}

type UpdateSemesterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSemesterRequest) Reset() {
	*x = UpdateSemesterRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSemesterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSemesterRequest) ProtoMessage() {}

func (x *UpdateSemesterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSemesterRequest.ProtoReflect.Descriptor instead.
func (*UpdateSemesterRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSemesterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSemesterRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateSemesterRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateSemesterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semester      *Semester              `protobuf:"bytes,1,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSemesterResponse) Reset() {
	*x = UpdateSemesterResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSemesterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSemesterResponse) ProtoMessage() {}

func (x *UpdateSemesterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSemesterResponse.ProtoReflect.Descriptor instead.
func (*UpdateSemesterResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSemesterResponse) GetSemester() *Semester {
	if x != nil {
		return x.Semester
	}
	return nil
}

type DeleteSemesterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSemesterRequest) Reset() {
	*x = DeleteSemesterRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSemesterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSemesterRequest) ProtoMessage() {}

func (x *DeleteSemesterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSemesterRequest.ProtoReflect.Descriptor instead.
func (*DeleteSemesterRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSemesterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSemesterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSemesterResponse) Reset() {
	*x = DeleteSemesterResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSemesterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSemesterResponse) ProtoMessage() {}

func (x *DeleteSemesterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSemesterResponse.ProtoReflect.Descriptor instead.
func (*DeleteSemesterResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSemesterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListSemestersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *common.SearchRequest  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSemestersRequest) Reset() {
	*x = ListSemestersRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSemestersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSemestersRequest) ProtoMessage() {}

func (x *ListSemestersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSemestersRequest.ProtoReflect.Descriptor instead.
func (*ListSemestersRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{9}
}

func (x *ListSemestersRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListSemestersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semesters     []*Semester            `protobuf:"bytes,1,rep,name=semesters,proto3" json:"semesters,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSemestersResponse) Reset() {
	*x = ListSemestersResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSemestersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSemestersResponse) ProtoMessage() {}

func (x *ListSemestersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSemestersResponse.ProtoReflect.Descriptor instead.
func (*ListSemestersResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{10}
}

func (x *ListSemestersResponse) GetSemesters() []*Semester {
	if x != nil {
		return x.Semesters
	}
	return nil
}

func (x *ListSemestersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSemestersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSemestersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ============= Faculty =============
type Faculty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Ms            string                 `protobuf:"bytes,7,opt,name=ms,proto3" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faculty) Reset() {
	*x = Faculty{}
	mi := &file_proto_academic_academic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faculty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faculty) ProtoMessage() {}

func (x *Faculty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faculty.ProtoReflect.Descriptor instead.
func (*Faculty) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{11}
}

func (x *Faculty) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Faculty) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Faculty) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Faculty) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Faculty) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Faculty) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Faculty) GetMs() string {
	if x != nil {
		return x.Ms
	}
	return ""
}

type CreateFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Ms            string                 `protobuf:"bytes,6,opt,name=ms,proto3" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacultyRequest) Reset() {
	*x = CreateFacultyRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacultyRequest) ProtoMessage() {}

func (x *CreateFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacultyRequest.ProtoReflect.Descriptor instead.
func (*CreateFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{12}
}

func (x *CreateFacultyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateFacultyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFacultyRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateFacultyRequest) GetMs() string {
	if x != nil {
		return x.Ms
	}
	return ""
}

type CreateFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       *Faculty               `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacultyResponse) Reset() {
	*x = CreateFacultyResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacultyResponse) ProtoMessage() {}

func (x *CreateFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacultyResponse.ProtoReflect.Descriptor instead.
func (*CreateFacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{13}
}

func (x *CreateFacultyResponse) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type GetFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacultyRequest) Reset() {
	*x = GetFacultyRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacultyRequest) ProtoMessage() {}

func (x *GetFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacultyRequest.ProtoReflect.Descriptor instead.
func (*GetFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{14}
}

func (x *GetFacultyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       *Faculty               `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacultyResponse) Reset() {
	*x = GetFacultyResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacultyResponse) ProtoMessage() {}

func (x *GetFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacultyResponse.ProtoReflect.Descriptor instead.
func (*GetFacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{15}
}

func (x *GetFacultyResponse) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type UpdateFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Ms            *string                `protobuf:"bytes,4,opt,name=ms,proto3,oneof" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacultyRequest) Reset() {
	*x = UpdateFacultyRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacultyRequest) ProtoMessage() {}

func (x *UpdateFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacultyRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateFacultyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFacultyRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateFacultyRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateFacultyRequest) GetMs() string {
	if x != nil && x.Ms != nil {
		return *x.Ms
	}
	return ""
}

type UpdateFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       *Faculty               `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacultyResponse) Reset() {
	*x = UpdateFacultyResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacultyResponse) ProtoMessage() {}

func (x *UpdateFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacultyResponse.ProtoReflect.Descriptor instead.
func (*UpdateFacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateFacultyResponse) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type DeleteFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacultyRequest) Reset() {
	*x = DeleteFacultyRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacultyRequest) ProtoMessage() {}

func (x *DeleteFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacultyRequest.ProtoReflect.Descriptor instead.
func (*DeleteFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteFacultyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacultyResponse) Reset() {
	*x = DeleteFacultyResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacultyResponse) ProtoMessage() {}

func (x *DeleteFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacultyResponse.ProtoReflect.Descriptor instead.
func (*DeleteFacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteFacultyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFacultiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *common.SearchRequest  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacultiesRequest) Reset() {
	*x = ListFacultiesRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacultiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacultiesRequest) ProtoMessage() {}

func (x *ListFacultiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacultiesRequest.ProtoReflect.Descriptor instead.
func (*ListFacultiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{20}
}

func (x *ListFacultiesRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListFacultiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculties     []*Faculty             `protobuf:"bytes,1,rep,name=faculties,proto3" json:"faculties,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacultiesResponse) Reset() {
	*x = ListFacultiesResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacultiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacultiesResponse) ProtoMessage() {}

func (x *ListFacultiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacultiesResponse.ProtoReflect.Descriptor instead.
func (*ListFacultiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{21}
}

func (x *ListFacultiesResponse) GetFaculties() []*Faculty {
	if x != nil {
		return x.Faculties
	}
	return nil
}

func (x *ListFacultiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFacultiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFacultiesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ============= Major =============
type Major struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FacultyCode   string                 `protobuf:"bytes,3,opt,name=faculty_code,json=facultyCode,proto3" json:"faculty_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Ms            string                 `protobuf:"bytes,8,opt,name=ms,proto3" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Major) Reset() {
	*x = Major{}
	mi := &file_proto_academic_academic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Major) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Major) ProtoMessage() {}

func (x *Major) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Major.ProtoReflect.Descriptor instead.
func (*Major) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{22}
}

func (x *Major) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Major) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Major) GetFacultyCode() string {
	if x != nil {
		return x.FacultyCode
	}
	return ""
}

func (x *Major) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Major) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Major) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Major) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Major) GetMs() string {
	if x != nil {
		return x.Ms
	}
	return ""
}

type CreateMajorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	FacultyCode   string                 `protobuf:"bytes,2,opt,name=faculty_code,json=facultyCode,proto3" json:"faculty_code,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Ms            string                 `protobuf:"bytes,4,opt,name=ms,proto3" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMajorRequest) Reset() {
	*x = CreateMajorRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMajorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMajorRequest) ProtoMessage() {}

func (x *CreateMajorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMajorRequest.ProtoReflect.Descriptor instead.
func (*CreateMajorRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{23}
}

func (x *CreateMajorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMajorRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMajorRequest) GetFacultyCode() string {
	if x != nil {
		return x.FacultyCode
	}
	return ""
}

func (x *CreateMajorRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateMajorRequest) GetMs() string {
	if x != nil {
		return x.Ms
	}
	return ""
}

type CreateMajorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *Major                 `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMajorResponse) Reset() {
	*x = CreateMajorResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMajorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMajorResponse) ProtoMessage() {}

func (x *CreateMajorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMajorResponse.ProtoReflect.Descriptor instead.
func (*CreateMajorResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{24}
}

func (x *CreateMajorResponse) GetMajor() *Major {
	if x != nil {
		return x.Major
	}
	return nil
}

type GetMajorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMajorRequest) Reset() {
	*x = GetMajorRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMajorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMajorRequest) ProtoMessage() {}

func (x *GetMajorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMajorRequest.ProtoReflect.Descriptor instead.
func (*GetMajorRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{25}
}

func (x *GetMajorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMajorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *Major                 `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMajorResponse) Reset() {
	*x = GetMajorResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMajorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMajorResponse) ProtoMessage() {}

func (x *GetMajorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMajorResponse.ProtoReflect.Descriptor instead.
func (*GetMajorResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{26}
}

func (x *GetMajorResponse) GetMajor() *Major {
	if x != nil {
		return x.Major
	}
	return nil
}

type UpdateMajorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	FacultyCode   *string                `protobuf:"bytes,3,opt,name=faculty_code,json=facultyCode,proto3,oneof" json:"faculty_code,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Ms            *string                `protobuf:"bytes,5,opt,name=ms,proto3,oneof" json:"ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMajorRequest) Reset() {
	*x = UpdateMajorRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMajorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMajorRequest) ProtoMessage() {}

func (x *UpdateMajorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMajorRequest.ProtoReflect.Descriptor instead.
func (*UpdateMajorRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateMajorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMajorRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateMajorRequest) GetFacultyCode() string {
	if x != nil && x.FacultyCode != nil {
		return *x.FacultyCode
	}
	return ""
}

func (x *UpdateMajorRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateMajorRequest) GetMs() string {
	if x != nil && x.Ms != nil {
		return *x.Ms
	}
	return ""
}

type UpdateMajorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *Major                 `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMajorResponse) Reset() {
	*x = UpdateMajorResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMajorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMajorResponse) ProtoMessage() {}

func (x *UpdateMajorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMajorResponse.ProtoReflect.Descriptor instead.
func (*UpdateMajorResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateMajorResponse) GetMajor() *Major {
	if x != nil {
		return x.Major
	}
	return nil
}

type DeleteMajorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMajorRequest) Reset() {
	*x = DeleteMajorRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMajorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMajorRequest) ProtoMessage() {}

func (x *DeleteMajorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMajorRequest.ProtoReflect.Descriptor instead.
func (*DeleteMajorRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteMajorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMajorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMajorResponse) Reset() {
	*x = DeleteMajorResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMajorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMajorResponse) ProtoMessage() {}

func (x *DeleteMajorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMajorResponse.ProtoReflect.Descriptor instead.
func (*DeleteMajorResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteMajorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMajorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *common.SearchRequest  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMajorsRequest) Reset() {
	*x = ListMajorsRequest{}
	mi := &file_proto_academic_academic_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMajorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMajorsRequest) ProtoMessage() {}

func (x *ListMajorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMajorsRequest.ProtoReflect.Descriptor instead.
func (*ListMajorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{31}
}

func (x *ListMajorsRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListMajorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Majors        []*Major               `protobuf:"bytes,1,rep,name=majors,proto3" json:"majors,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMajorsResponse) Reset() {
	*x = ListMajorsResponse{}
	mi := &file_proto_academic_academic_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMajorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMajorsResponse) ProtoMessage() {}

func (x *ListMajorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_academic_academic_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMajorsResponse.ProtoReflect.Descriptor instead.
func (*ListMajorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_academic_academic_proto_rawDescGZIP(), []int{32}
}

func (x *ListMajorsResponse) GetMajors() []*Major {
	if x != nil {
		return x.Majors
	}
	return nil
}

func (x *ListMajorsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMajorsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMajorsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_academic_academic_proto protoreflect.FileDescriptor

const file_proto_academic_academic_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/academic/academic.proto\x12\bacademic\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xe4\x01\n" +
	"\bSemester\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\"L\n" +
	"\x15CreateSemesterRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\"H\n" +
	"\x16CreateSemesterResponse\x12.\n" +
	"\bsemester\x18\x01 \x01(\v2\x12.academic.SemesterR\bsemester\"$\n" +
	"\x12GetSemesterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetSemesterResponse\x12.\n" +
	"\bsemester\x18\x01 \x01(\v2\x12.academic.SemesterR\bsemester\"k\n" +
	"\x15UpdateSemesterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedByB\b\n" +
	"\x06_title\"H\n" +
	"\x16UpdateSemesterResponse\x12.\n" +
	"\bsemester\x18\x01 \x01(\v2\x12.academic.SemesterR\bsemester\"'\n" +
	"\x15DeleteSemesterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteSemesterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x14ListSemestersRequest\x12-\n" +
	"\x06search\x18\x01 \x01(\v2\x15.common.SearchRequestR\x06search\"\x90\x01\n" +
	"\x15ListSemestersResponse\x120\n" +
	"\tsemesters\x18\x01 \x03(\v2\x12.academic.SemesterR\tsemesters\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xf3\x01\n" +
	"\aFaculty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\x12\x0e\n" +
	"\x02ms\x18\a \x01(\tR\x02ms\"k\n" +
	"\x14CreateFacultyRequest\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x0e\n" +
	"\x02ms\x18\x06 \x01(\tR\x02ms\"D\n" +
	"\x15CreateFacultyResponse\x12+\n" +
	"\afaculty\x18\x01 \x01(\v2\x11.academic.FacultyR\afaculty\"#\n" +
	"\x11GetFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x12GetFacultyResponse\x12+\n" +
	"\afaculty\x18\x01 \x01(\v2\x11.academic.FacultyR\afaculty\"\x86\x01\n" +
	"\x14UpdateFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x12\x13\n" +
	"\x02ms\x18\x04 \x01(\tH\x01R\x02ms\x88\x01\x01B\b\n" +
	"\x06_titleB\x05\n" +
	"\x03_ms\"D\n" +
	"\x15UpdateFacultyResponse\x12+\n" +
	"\afaculty\x18\x01 \x01(\v2\x11.academic.FacultyR\afaculty\"&\n" +
	"\x14DeleteFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteFacultyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x14ListFacultiesRequest\x12-\n" +
	"\x06search\x18\x01 \x01(\v2\x15.common.SearchRequestR\x06search\"\x8f\x01\n" +
	"\x15ListFacultiesResponse\x12/\n" +
	"\tfaculties\x18\x01 \x03(\v2\x11.academic.FacultyR\tfaculties\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x94\x02\n" +
	"\x05Major\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\ffaculty_code\x18\x03 \x01(\tR\vfacultyCode\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\x12\x0e\n" +
	"\x02ms\x18\b \x01(\tR\x02ms\"\x8c\x01\n" +
	"\x12CreateMajorRequest\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\ffaculty_code\x18\x02 \x01(\tR\vfacultyCode\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12\x0e\n" +
	"\x02ms\x18\x04 \x01(\tR\x02ms\"<\n" +
	"\x13CreateMajorResponse\x12%\n" +
	"\x05major\x18\x01 \x01(\v2\x0f.academic.MajorR\x05major\"!\n" +
	"\x0fGetMajorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetMajorResponse\x12%\n" +
	"\x05major\x18\x01 \x01(\v2\x0f.academic.MajorR\x05major\"\xbd\x01\n" +
	"\x12UpdateMajorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12&\n" +
	"\ffaculty_code\x18\x03 \x01(\tH\x01R\vfacultyCode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\x12\x13\n" +
	"\x02ms\x18\x05 \x01(\tH\x02R\x02ms\x88\x01\x01B\b\n" +
	"\x06_titleB\x0f\n" +
	"\r_faculty_codeB\x05\n" +
	"\x03_ms\"<\n" +
	"\x13UpdateMajorResponse\x12%\n" +
	"\x05major\x18\x01 \x01(\v2\x0f.academic.MajorR\x05major\"$\n" +
	"\x12DeleteMajorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteMajorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x11ListMajorsRequest\x12-\n" +
	"\x06search\x18\x01 \x01(\v2\x15.common.SearchRequestR\x06search\"\x84\x01\n" +
	"\x12ListMajorsResponse\x12'\n" +
	"\x06majors\x18\x01 \x03(\v2\x0f.academic.MajorR\x06majors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xaf\t\n" +
	"\x0fAcademicService\x12S\n" +
	"\x0eCreateSemester\x12\x1f.academic.CreateSemesterRequest\x1a .academic.CreateSemesterResponse\x12J\n" +
	"\vGetSemester\x12\x1c.academic.GetSemesterRequest\x1a\x1d.academic.GetSemesterResponse\x12S\n" +
	"\x0eUpdateSemester\x12\x1f.academic.UpdateSemesterRequest\x1a .academic.UpdateSemesterResponse\x12S\n" +
	"\x0eDeleteSemester\x12\x1f.academic.DeleteSemesterRequest\x1a .academic.DeleteSemesterResponse\x12P\n" +
	"\rListSemesters\x12\x1e.academic.ListSemestersRequest\x1a\x1f.academic.ListSemestersResponse\x12P\n" +
	"\rCreateFaculty\x12\x1e.academic.CreateFacultyRequest\x1a\x1f.academic.CreateFacultyResponse\x12G\n" +
	"\n" +
	"GetFaculty\x12\x1b.academic.GetFacultyRequest\x1a\x1c.academic.GetFacultyResponse\x12P\n" +
	"\rUpdateFaculty\x12\x1e.academic.UpdateFacultyRequest\x1a\x1f.academic.UpdateFacultyResponse\x12P\n" +
	"\rDeleteFaculty\x12\x1e.academic.DeleteFacultyRequest\x1a\x1f.academic.DeleteFacultyResponse\x12P\n" +
	"\rListFaculties\x12\x1e.academic.ListFacultiesRequest\x1a\x1f.academic.ListFacultiesResponse\x12J\n" +
	"\vCreateMajor\x12\x1c.academic.CreateMajorRequest\x1a\x1d.academic.CreateMajorResponse\x12A\n" +
	"\bGetMajor\x12\x19.academic.GetMajorRequest\x1a\x1a.academic.GetMajorResponse\x12J\n" +
	"\vUpdateMajor\x12\x1c.academic.UpdateMajorRequest\x1a\x1d.academic.UpdateMajorResponse\x12J\n" +
	"\vDeleteMajor\x12\x1c.academic.DeleteMajorRequest\x1a\x1d.academic.DeleteMajorResponse\x12G\n" +
	"\n" +
	"ListMajors\x12\x1b.academic.ListMajorsRequest\x1a\x1c.academic.ListMajorsResponseB\fZ\n" +
	"./academicb\x06proto3"

var (
	file_proto_academic_academic_proto_rawDescOnce sync.Once
	file_proto_academic_academic_proto_rawDescData []byte
)

func file_proto_academic_academic_proto_rawDescGZIP() []byte {
	file_proto_academic_academic_proto_rawDescOnce.Do(func() {
		file_proto_academic_academic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_academic_academic_proto_rawDesc), len(file_proto_academic_academic_proto_rawDesc)))
	})
	return file_proto_academic_academic_proto_rawDescData
}

var file_proto_academic_academic_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_academic_academic_proto_goTypes = []any{
	(*Semester)(nil),               // 0: academic.Semester
	(*CreateSemesterRequest)(nil),  // 1: academic.CreateSemesterRequest
	(*CreateSemesterResponse)(nil), // 2: academic.CreateSemesterResponse
	(*GetSemesterRequest)(nil),     // 3: academic.GetSemesterRequest
	(*GetSemesterResponse)(nil),    // 4: academic.GetSemesterResponse
	(*UpdateSemesterRequest)(nil),  // 5: academic.UpdateSemesterRequest
	(*UpdateSemesterResponse)(nil), // 6: academic.UpdateSemesterResponse
	(*DeleteSemesterRequest)(nil),  // 7: academic.DeleteSemesterRequest
	(*DeleteSemesterResponse)(nil), // 8: academic.DeleteSemesterResponse
	(*ListSemestersRequest)(nil),   // 9: academic.ListSemestersRequest
	(*ListSemestersResponse)(nil),  // 10: academic.ListSemestersResponse
	(*Faculty)(nil),                // 11: academic.Faculty
	(*CreateFacultyRequest)(nil),   // 12: academic.CreateFacultyRequest
	(*CreateFacultyResponse)(nil),  // 13: academic.CreateFacultyResponse
	(*GetFacultyRequest)(nil),      // 14: academic.GetFacultyRequest
	(*GetFacultyResponse)(nil),     // 15: academic.GetFacultyResponse
	(*UpdateFacultyRequest)(nil),   // 16: academic.UpdateFacultyRequest
	(*UpdateFacultyResponse)(nil),  // 17: academic.UpdateFacultyResponse
	(*DeleteFacultyRequest)(nil),   // 18: academic.DeleteFacultyRequest
	(*DeleteFacultyResponse)(nil),  // 19: academic.DeleteFacultyResponse
	(*ListFacultiesRequest)(nil),   // 20: academic.ListFacultiesRequest
	(*ListFacultiesResponse)(nil),  // 21: academic.ListFacultiesResponse
	(*Major)(nil),                  // 22: academic.Major
	(*CreateMajorRequest)(nil),     // 23: academic.CreateMajorRequest
	(*CreateMajorResponse)(nil),    // 24: academic.CreateMajorResponse
	(*GetMajorRequest)(nil),        // 25: academic.GetMajorRequest
	(*GetMajorResponse)(nil),       // 26: academic.GetMajorResponse
	(*UpdateMajorRequest)(nil),     // 27: academic.UpdateMajorRequest
	(*UpdateMajorResponse)(nil),    // 28: academic.UpdateMajorResponse
	(*DeleteMajorRequest)(nil),     // 29: academic.DeleteMajorRequest
	(*DeleteMajorResponse)(nil),    // 30: academic.DeleteMajorResponse
	(*ListMajorsRequest)(nil),      // 31: academic.ListMajorsRequest
	(*ListMajorsResponse)(nil),     // 32: academic.ListMajorsResponse
	(*timestamppb.Timestamp)(nil),  // 33: google.protobuf.Timestamp
	(*common.SearchRequest)(nil),   // 34: common.SearchRequest
}
var file_proto_academic_academic_proto_depIdxs = []int32{
	33, // 0: academic.Semester.created_at:type_name -> google.protobuf.Timestamp
	33, // 1: academic.Semester.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: academic.CreateSemesterResponse.semester:type_name -> academic.Semester
	0,  // 3: academic.GetSemesterResponse.semester:type_name -> academic.Semester
	0,  // 4: academic.UpdateSemesterResponse.semester:type_name -> academic.Semester
	34, // 5: academic.ListSemestersRequest.search:type_name -> common.SearchRequest
	0,  // 6: academic.ListSemestersResponse.semesters:type_name -> academic.Semester
	33, // 7: academic.Faculty.created_at:type_name -> google.protobuf.Timestamp
	33, // 8: academic.Faculty.updated_at:type_name -> google.protobuf.Timestamp
	11, // 9: academic.CreateFacultyResponse.faculty:type_name -> academic.Faculty
	11, // 10: academic.GetFacultyResponse.faculty:type_name -> academic.Faculty
	11, // 11: academic.UpdateFacultyResponse.faculty:type_name -> academic.Faculty
	34, // 12: academic.ListFacultiesRequest.search:type_name -> common.SearchRequest
	11, // 13: academic.ListFacultiesResponse.faculties:type_name -> academic.Faculty
	33, // 14: academic.Major.created_at:type_name -> google.protobuf.Timestamp
	33, // 15: academic.Major.updated_at:type_name -> google.protobuf.Timestamp
	22, // 16: academic.CreateMajorResponse.major:type_name -> academic.Major
	22, // 17: academic.GetMajorResponse.major:type_name -> academic.Major
	22, // 18: academic.UpdateMajorResponse.major:type_name -> academic.Major
	34, // 19: academic.ListMajorsRequest.search:type_name -> common.SearchRequest
	22, // 20: academic.ListMajorsResponse.majors:type_name -> academic.Major
	1,  // 21: academic.AcademicService.CreateSemester:input_type -> academic.CreateSemesterRequest
	3,  // 22: academic.AcademicService.GetSemester:input_type -> academic.GetSemesterRequest
	5,  // 23: academic.AcademicService.UpdateSemester:input_type -> academic.UpdateSemesterRequest
	7,  // 24: academic.AcademicService.DeleteSemester:input_type -> academic.DeleteSemesterRequest
	9,  // 25: academic.AcademicService.ListSemesters:input_type -> academic.ListSemestersRequest
	12, // 26: academic.AcademicService.CreateFaculty:input_type -> academic.CreateFacultyRequest
	14, // 27: academic.AcademicService.GetFaculty:input_type -> academic.GetFacultyRequest
	16, // 28: academic.AcademicService.UpdateFaculty:input_type -> academic.UpdateFacultyRequest
	18, // 29: academic.AcademicService.DeleteFaculty:input_type -> academic.DeleteFacultyRequest
	20, // 30: academic.AcademicService.ListFaculties:input_type -> academic.ListFacultiesRequest
	23, // 31: academic.AcademicService.CreateMajor:input_type -> academic.CreateMajorRequest
	25, // 32: academic.AcademicService.GetMajor:input_type -> academic.GetMajorRequest
	27, // 33: academic.AcademicService.UpdateMajor:input_type -> academic.UpdateMajorRequest
	29, // 34: academic.AcademicService.DeleteMajor:input_type -> academic.DeleteMajorRequest
	31, // 35: academic.AcademicService.ListMajors:input_type -> academic.ListMajorsRequest
	2,  // 36: academic.AcademicService.CreateSemester:output_type -> academic.CreateSemesterResponse
	4,  // 37: academic.AcademicService.GetSemester:output_type -> academic.GetSemesterResponse
	6,  // 38: academic.AcademicService.UpdateSemester:output_type -> academic.UpdateSemesterResponse
	8,  // 39: academic.AcademicService.DeleteSemester:output_type -> academic.DeleteSemesterResponse
	10, // 40: academic.AcademicService.ListSemesters:output_type -> academic.ListSemestersResponse
	13, // 41: academic.AcademicService.CreateFaculty:output_type -> academic.CreateFacultyResponse
	15, // 42: academic.AcademicService.GetFaculty:output_type -> academic.GetFacultyResponse
	17, // 43: academic.AcademicService.UpdateFaculty:output_type -> academic.UpdateFacultyResponse
	19, // 44: academic.AcademicService.DeleteFaculty:output_type -> academic.DeleteFacultyResponse
	21, // 45: academic.AcademicService.ListFaculties:output_type -> academic.ListFacultiesResponse
	24, // 46: academic.AcademicService.CreateMajor:output_type -> academic.CreateMajorResponse
	26, // 47: academic.AcademicService.GetMajor:output_type -> academic.GetMajorResponse
	28, // 48: academic.AcademicService.UpdateMajor:output_type -> academic.UpdateMajorResponse
	30, // 49: academic.AcademicService.DeleteMajor:output_type -> academic.DeleteMajorResponse
	32, // 50: academic.AcademicService.ListMajors:output_type -> academic.ListMajorsResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_academic_academic_proto_init() }
func file_proto_academic_academic_proto_init() {
	if File_proto_academic_academic_proto != nil {
		return
	}
	file_proto_academic_academic_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_academic_academic_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_academic_academic_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_academic_academic_proto_rawDesc), len(file_proto_academic_academic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_academic_academic_proto_goTypes,
		DependencyIndexes: file_proto_academic_academic_proto_depIdxs,
		MessageInfos:      file_proto_academic_academic_proto_msgTypes,
	}.Build()
	File_proto_academic_academic_proto = out.File
	file_proto_academic_academic_proto_goTypes = nil
	file_proto_academic_academic_proto_depIdxs = nil
}
