// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/role/role.proto

package role

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoleService_CreateRoleSystem_FullMethodName = "/role.RoleService/CreateRoleSystem"
	RoleService_GetRoleSystem_FullMethodName    = "/role.RoleService/GetRoleSystem"
	RoleService_UpdateRoleSystem_FullMethodName = "/role.RoleService/UpdateRoleSystem"
	RoleService_DeleteRoleSystem_FullMethodName = "/role.RoleService/DeleteRoleSystem"
	RoleService_ListRoleSystems_FullMethodName  = "/role.RoleService/ListRoleSystems"
)

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============= Service =============
type RoleServiceClient interface {
	CreateRoleSystem(ctx context.Context, in *CreateRoleSystemRequest, opts ...grpc.CallOption) (*CreateRoleSystemResponse, error)
	GetRoleSystem(ctx context.Context, in *GetRoleSystemRequest, opts ...grpc.CallOption) (*GetRoleSystemResponse, error)
	UpdateRoleSystem(ctx context.Context, in *UpdateRoleSystemRequest, opts ...grpc.CallOption) (*UpdateRoleSystemResponse, error)
	DeleteRoleSystem(ctx context.Context, in *DeleteRoleSystemRequest, opts ...grpc.CallOption) (*DeleteRoleSystemResponse, error)
	ListRoleSystems(ctx context.Context, in *ListRoleSystemsRequest, opts ...grpc.CallOption) (*ListRoleSystemsResponse, error)
}

type roleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleServiceClient(cc grpc.ClientConnInterface) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) CreateRoleSystem(ctx context.Context, in *CreateRoleSystemRequest, opts ...grpc.CallOption) (*CreateRoleSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleSystemResponse)
	err := c.cc.Invoke(ctx, RoleService_CreateRoleSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRoleSystem(ctx context.Context, in *GetRoleSystemRequest, opts ...grpc.CallOption) (*GetRoleSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleSystemResponse)
	err := c.cc.Invoke(ctx, RoleService_GetRoleSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdateRoleSystem(ctx context.Context, in *UpdateRoleSystemRequest, opts ...grpc.CallOption) (*UpdateRoleSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleSystemResponse)
	err := c.cc.Invoke(ctx, RoleService_UpdateRoleSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) DeleteRoleSystem(ctx context.Context, in *DeleteRoleSystemRequest, opts ...grpc.CallOption) (*DeleteRoleSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleSystemResponse)
	err := c.cc.Invoke(ctx, RoleService_DeleteRoleSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) ListRoleSystems(ctx context.Context, in *ListRoleSystemsRequest, opts ...grpc.CallOption) (*ListRoleSystemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleSystemsResponse)
	err := c.cc.Invoke(ctx, RoleService_ListRoleSystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
// All implementations must embed UnimplementedRoleServiceServer
// for forward compatibility.
//
// ============= Service =============
type RoleServiceServer interface {
	CreateRoleSystem(context.Context, *CreateRoleSystemRequest) (*CreateRoleSystemResponse, error)
	GetRoleSystem(context.Context, *GetRoleSystemRequest) (*GetRoleSystemResponse, error)
	UpdateRoleSystem(context.Context, *UpdateRoleSystemRequest) (*UpdateRoleSystemResponse, error)
	DeleteRoleSystem(context.Context, *DeleteRoleSystemRequest) (*DeleteRoleSystemResponse, error)
	ListRoleSystems(context.Context, *ListRoleSystemsRequest) (*ListRoleSystemsResponse, error)
	mustEmbedUnimplementedRoleServiceServer()
}

// UnimplementedRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleServiceServer struct{}

func (UnimplementedRoleServiceServer) CreateRoleSystem(context.Context, *CreateRoleSystemRequest) (*CreateRoleSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoleSystem not implemented")
}
func (UnimplementedRoleServiceServer) GetRoleSystem(context.Context, *GetRoleSystemRequest) (*GetRoleSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleSystem not implemented")
}
func (UnimplementedRoleServiceServer) UpdateRoleSystem(context.Context, *UpdateRoleSystemRequest) (*UpdateRoleSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleSystem not implemented")
}
func (UnimplementedRoleServiceServer) DeleteRoleSystem(context.Context, *DeleteRoleSystemRequest) (*DeleteRoleSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoleSystem not implemented")
}
func (UnimplementedRoleServiceServer) ListRoleSystems(context.Context, *ListRoleSystemsRequest) (*ListRoleSystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoleSystems not implemented")
}
func (UnimplementedRoleServiceServer) mustEmbedUnimplementedRoleServiceServer() {}
func (UnimplementedRoleServiceServer) testEmbeddedByValue()                     {}

// UnsafeRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServiceServer will
// result in compilation errors.
type UnsafeRoleServiceServer interface {
	mustEmbedUnimplementedRoleServiceServer()
}

func RegisterRoleServiceServer(s grpc.ServiceRegistrar, srv RoleServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleService_ServiceDesc, srv)
}

func _RoleService_CreateRoleSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).CreateRoleSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_CreateRoleSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).CreateRoleSystem(ctx, req.(*CreateRoleSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRoleSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRoleSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_GetRoleSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRoleSystem(ctx, req.(*GetRoleSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdateRoleSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdateRoleSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_UpdateRoleSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdateRoleSystem(ctx, req.(*UpdateRoleSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_DeleteRoleSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).DeleteRoleSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_DeleteRoleSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).DeleteRoleSystem(ctx, req.(*DeleteRoleSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_ListRoleSystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).ListRoleSystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_ListRoleSystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).ListRoleSystems(ctx, req.(*ListRoleSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleService_ServiceDesc is the grpc.ServiceDesc for RoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "role.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoleSystem",
			Handler:    _RoleService_CreateRoleSystem_Handler,
		},
		{
			MethodName: "GetRoleSystem",
			Handler:    _RoleService_GetRoleSystem_Handler,
		},
		{
			MethodName: "UpdateRoleSystem",
			Handler:    _RoleService_UpdateRoleSystem_Handler,
		},
		{
			MethodName: "DeleteRoleSystem",
			Handler:    _RoleService_DeleteRoleSystem_Handler,
		},
		{
			MethodName: "ListRoleSystems",
			Handler:    _RoleService_ListRoleSystems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/role/role.proto",
}
