// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/role/role.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common "thaily/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleType int32

const (
	RoleType_ACADEMIC_AFFAIRS_STAFF RoleType = 0
	RoleType_DEPARTMENT_LECTURER    RoleType = 1
	RoleType_TEACHER                RoleType = 2
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ACADEMIC_AFFAIRS_STAFF",
		1: "DEPARTMENT_LECTURER",
		2: "TEACHER",
	}
	RoleType_value = map[string]int32{
		"ACADEMIC_AFFAIRS_STAFF": 0,
		"DEPARTMENT_LECTURER":    1,
		"TEACHER":                2,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_role_role_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_proto_role_role_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{0}
}

// ============= RoleSystem =============
type RoleSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TeacherCode   string                 `protobuf:"bytes,3,opt,name=teacher_code,json=teacherCode,proto3" json:"teacher_code,omitempty"`
	Role          RoleType               `protobuf:"varint,4,opt,name=role,proto3,enum=role.RoleType" json:"role,omitempty"`
	SemesterCode  string                 `protobuf:"bytes,5,opt,name=semester_code,json=semesterCode,proto3" json:"semester_code,omitempty"`
	Activate      bool                   `protobuf:"varint,6,opt,name=activate,proto3" json:"activate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSystem) Reset() {
	*x = RoleSystem{}
	mi := &file_proto_role_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSystem) ProtoMessage() {}

func (x *RoleSystem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSystem.ProtoReflect.Descriptor instead.
func (*RoleSystem) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleSystem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleSystem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleSystem) GetTeacherCode() string {
	if x != nil {
		return x.TeacherCode
	}
	return ""
}

func (x *RoleSystem) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ACADEMIC_AFFAIRS_STAFF
}

func (x *RoleSystem) GetSemesterCode() string {
	if x != nil {
		return x.SemesterCode
	}
	return ""
}

func (x *RoleSystem) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *RoleSystem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleSystem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RoleSystem) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RoleSystem) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type CreateRoleSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TeacherCode   string                 `protobuf:"bytes,2,opt,name=teacher_code,json=teacherCode,proto3" json:"teacher_code,omitempty"`
	Role          RoleType               `protobuf:"varint,3,opt,name=role,proto3,enum=role.RoleType" json:"role,omitempty"`
	SemesterCode  string                 `protobuf:"bytes,4,opt,name=semester_code,json=semesterCode,proto3" json:"semester_code,omitempty"`
	Activate      bool                   `protobuf:"varint,5,opt,name=activate,proto3" json:"activate,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleSystemRequest) Reset() {
	*x = CreateRoleSystemRequest{}
	mi := &file_proto_role_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleSystemRequest) ProtoMessage() {}

func (x *CreateRoleSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleSystemRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleSystemRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleSystemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoleSystemRequest) GetTeacherCode() string {
	if x != nil {
		return x.TeacherCode
	}
	return ""
}

func (x *CreateRoleSystemRequest) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ACADEMIC_AFFAIRS_STAFF
}

func (x *CreateRoleSystemRequest) GetSemesterCode() string {
	if x != nil {
		return x.SemesterCode
	}
	return ""
}

func (x *CreateRoleSystemRequest) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *CreateRoleSystemRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateRoleSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleSystem    *RoleSystem            `protobuf:"bytes,1,opt,name=role_system,json=roleSystem,proto3" json:"role_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleSystemResponse) Reset() {
	*x = CreateRoleSystemResponse{}
	mi := &file_proto_role_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleSystemResponse) ProtoMessage() {}

func (x *CreateRoleSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleSystemResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleSystemResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleSystemResponse) GetRoleSystem() *RoleSystem {
	if x != nil {
		return x.RoleSystem
	}
	return nil
}

type GetRoleSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleSystemRequest) Reset() {
	*x = GetRoleSystemRequest{}
	mi := &file_proto_role_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleSystemRequest) ProtoMessage() {}

func (x *GetRoleSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleSystemRequest.ProtoReflect.Descriptor instead.
func (*GetRoleSystemRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleSystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoleSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleSystem    *RoleSystem            `protobuf:"bytes,1,opt,name=role_system,json=roleSystem,proto3" json:"role_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleSystemResponse) Reset() {
	*x = GetRoleSystemResponse{}
	mi := &file_proto_role_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleSystemResponse) ProtoMessage() {}

func (x *GetRoleSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleSystemResponse.ProtoReflect.Descriptor instead.
func (*GetRoleSystemResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoleSystemResponse) GetRoleSystem() *RoleSystem {
	if x != nil {
		return x.RoleSystem
	}
	return nil
}

type UpdateRoleSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	TeacherCode   *string                `protobuf:"bytes,3,opt,name=teacher_code,json=teacherCode,proto3,oneof" json:"teacher_code,omitempty"`
	Role          *RoleType              `protobuf:"varint,4,opt,name=role,proto3,enum=role.RoleType,oneof" json:"role,omitempty"`
	SemesterCode  *string                `protobuf:"bytes,5,opt,name=semester_code,json=semesterCode,proto3,oneof" json:"semester_code,omitempty"`
	Activate      *bool                  `protobuf:"varint,6,opt,name=activate,proto3,oneof" json:"activate,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleSystemRequest) Reset() {
	*x = UpdateRoleSystemRequest{}
	mi := &file_proto_role_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleSystemRequest) ProtoMessage() {}

func (x *UpdateRoleSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleSystemRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleSystemRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleSystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleSystemRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRoleSystemRequest) GetTeacherCode() string {
	if x != nil && x.TeacherCode != nil {
		return *x.TeacherCode
	}
	return ""
}

func (x *UpdateRoleSystemRequest) GetRole() RoleType {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return RoleType_ACADEMIC_AFFAIRS_STAFF
}

func (x *UpdateRoleSystemRequest) GetSemesterCode() string {
	if x != nil && x.SemesterCode != nil {
		return *x.SemesterCode
	}
	return ""
}

func (x *UpdateRoleSystemRequest) GetActivate() bool {
	if x != nil && x.Activate != nil {
		return *x.Activate
	}
	return false
}

func (x *UpdateRoleSystemRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateRoleSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleSystem    *RoleSystem            `protobuf:"bytes,1,opt,name=role_system,json=roleSystem,proto3" json:"role_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleSystemResponse) Reset() {
	*x = UpdateRoleSystemResponse{}
	mi := &file_proto_role_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleSystemResponse) ProtoMessage() {}

func (x *UpdateRoleSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleSystemResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleSystemResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleSystemResponse) GetRoleSystem() *RoleSystem {
	if x != nil {
		return x.RoleSystem
	}
	return nil
}

type DeleteRoleSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleSystemRequest) Reset() {
	*x = DeleteRoleSystemRequest{}
	mi := &file_proto_role_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleSystemRequest) ProtoMessage() {}

func (x *DeleteRoleSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleSystemRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleSystemRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoleSystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleSystemResponse) Reset() {
	*x = DeleteRoleSystemResponse{}
	mi := &file_proto_role_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleSystemResponse) ProtoMessage() {}

func (x *DeleteRoleSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleSystemResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleSystemResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleSystemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRoleSystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *common.SearchRequest  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleSystemsRequest) Reset() {
	*x = ListRoleSystemsRequest{}
	mi := &file_proto_role_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleSystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleSystemsRequest) ProtoMessage() {}

func (x *ListRoleSystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleSystemsRequest.ProtoReflect.Descriptor instead.
func (*ListRoleSystemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoleSystemsRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListRoleSystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleSystems   []*RoleSystem          `protobuf:"bytes,1,rep,name=role_systems,json=roleSystems,proto3" json:"role_systems,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleSystemsResponse) Reset() {
	*x = ListRoleSystemsResponse{}
	mi := &file_proto_role_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleSystemsResponse) ProtoMessage() {}

func (x *ListRoleSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleSystemsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleSystemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleSystemsResponse) GetRoleSystems() []*RoleSystem {
	if x != nil {
		return x.RoleSystems
	}
	return nil
}

func (x *ListRoleSystemsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRoleSystemsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoleSystemsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_role_role_proto protoreflect.FileDescriptor

const file_proto_role_role_proto_rawDesc = "" +
	"\n" +
	"\x15proto/role/role.proto\x12\x04role\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xee\x02\n" +
	"\n" +
	"RoleSystem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fteacher_code\x18\x03 \x01(\tR\vteacherCode\x12\"\n" +
	"\x04role\x18\x04 \x01(\x0e2\x0e.role.RoleTypeR\x04role\x12#\n" +
	"\rsemester_code\x18\x05 \x01(\tR\fsemesterCode\x12\x1a\n" +
	"\bactivate\x18\x06 \x01(\bR\bactivate\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\"\xd6\x01\n" +
	"\x17CreateRoleSystemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\fteacher_code\x18\x02 \x01(\tR\vteacherCode\x12\"\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0e.role.RoleTypeR\x04role\x12#\n" +
	"\rsemester_code\x18\x04 \x01(\tR\fsemesterCode\x12\x1a\n" +
	"\bactivate\x18\x05 \x01(\bR\bactivate\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\"M\n" +
	"\x18CreateRoleSystemResponse\x121\n" +
	"\vrole_system\x18\x01 \x01(\v2\x10.role.RoleSystemR\n" +
	"roleSystem\"&\n" +
	"\x14GetRoleSystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x15GetRoleSystemResponse\x121\n" +
	"\vrole_system\x18\x01 \x01(\v2\x10.role.RoleSystemR\n" +
	"roleSystem\"\xc2\x02\n" +
	"\x17UpdateRoleSystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12&\n" +
	"\fteacher_code\x18\x03 \x01(\tH\x01R\vteacherCode\x88\x01\x01\x12'\n" +
	"\x04role\x18\x04 \x01(\x0e2\x0e.role.RoleTypeH\x02R\x04role\x88\x01\x01\x12(\n" +
	"\rsemester_code\x18\x05 \x01(\tH\x03R\fsemesterCode\x88\x01\x01\x12\x1f\n" +
	"\bactivate\x18\x06 \x01(\bH\x04R\bactivate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedByB\b\n" +
	"\x06_titleB\x0f\n" +
	"\r_teacher_codeB\a\n" +
	"\x05_roleB\x10\n" +
	"\x0e_semester_codeB\v\n" +
	"\t_activate\"M\n" +
	"\x18UpdateRoleSystemResponse\x121\n" +
	"\vrole_system\x18\x01 \x01(\v2\x10.role.RoleSystemR\n" +
	"roleSystem\")\n" +
	"\x17DeleteRoleSystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteRoleSystemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x16ListRoleSystemsRequest\x12-\n" +
	"\x06search\x18\x01 \x01(\v2\x15.common.SearchRequestR\x06search\"\x95\x01\n" +
	"\x17ListRoleSystemsResponse\x123\n" +
	"\frole_systems\x18\x01 \x03(\v2\x10.role.RoleSystemR\vroleSystems\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*L\n" +
	"\bRoleType\x12\x1a\n" +
	"\x16ACADEMIC_AFFAIRS_STAFF\x10\x00\x12\x17\n" +
	"\x13DEPARTMENT_LECTURER\x10\x01\x12\v\n" +
	"\aTEACHER\x10\x022\xa0\x03\n" +
	"\vRoleService\x12Q\n" +
	"\x10CreateRoleSystem\x12\x1d.role.CreateRoleSystemRequest\x1a\x1e.role.CreateRoleSystemResponse\x12H\n" +
	"\rGetRoleSystem\x12\x1a.role.GetRoleSystemRequest\x1a\x1b.role.GetRoleSystemResponse\x12Q\n" +
	"\x10UpdateRoleSystem\x12\x1d.role.UpdateRoleSystemRequest\x1a\x1e.role.UpdateRoleSystemResponse\x12Q\n" +
	"\x10DeleteRoleSystem\x12\x1d.role.DeleteRoleSystemRequest\x1a\x1e.role.DeleteRoleSystemResponse\x12N\n" +
	"\x0fListRoleSystems\x12\x1c.role.ListRoleSystemsRequest\x1a\x1d.role.ListRoleSystemsResponseB\bZ\x06./roleb\x06proto3"

var (
	file_proto_role_role_proto_rawDescOnce sync.Once
	file_proto_role_role_proto_rawDescData []byte
)

func file_proto_role_role_proto_rawDescGZIP() []byte {
	file_proto_role_role_proto_rawDescOnce.Do(func() {
		file_proto_role_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_role_proto_rawDesc), len(file_proto_role_role_proto_rawDesc)))
	})
	return file_proto_role_role_proto_rawDescData
}

var file_proto_role_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_role_role_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_role_role_proto_goTypes = []any{
	(RoleType)(0),                    // 0: role.RoleType
	(*RoleSystem)(nil),               // 1: role.RoleSystem
	(*CreateRoleSystemRequest)(nil),  // 2: role.CreateRoleSystemRequest
	(*CreateRoleSystemResponse)(nil), // 3: role.CreateRoleSystemResponse
	(*GetRoleSystemRequest)(nil),     // 4: role.GetRoleSystemRequest
	(*GetRoleSystemResponse)(nil),    // 5: role.GetRoleSystemResponse
	(*UpdateRoleSystemRequest)(nil),  // 6: role.UpdateRoleSystemRequest
	(*UpdateRoleSystemResponse)(nil), // 7: role.UpdateRoleSystemResponse
	(*DeleteRoleSystemRequest)(nil),  // 8: role.DeleteRoleSystemRequest
	(*DeleteRoleSystemResponse)(nil), // 9: role.DeleteRoleSystemResponse
	(*ListRoleSystemsRequest)(nil),   // 10: role.ListRoleSystemsRequest
	(*ListRoleSystemsResponse)(nil),  // 11: role.ListRoleSystemsResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*common.SearchRequest)(nil),     // 13: common.SearchRequest
}
var file_proto_role_role_proto_depIdxs = []int32{
	0,  // 0: role.RoleSystem.role:type_name -> role.RoleType
	12, // 1: role.RoleSystem.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: role.RoleSystem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: role.CreateRoleSystemRequest.role:type_name -> role.RoleType
	1,  // 4: role.CreateRoleSystemResponse.role_system:type_name -> role.RoleSystem
	1,  // 5: role.GetRoleSystemResponse.role_system:type_name -> role.RoleSystem
	0,  // 6: role.UpdateRoleSystemRequest.role:type_name -> role.RoleType
	1,  // 7: role.UpdateRoleSystemResponse.role_system:type_name -> role.RoleSystem
	13, // 8: role.ListRoleSystemsRequest.search:type_name -> common.SearchRequest
	1,  // 9: role.ListRoleSystemsResponse.role_systems:type_name -> role.RoleSystem
	2,  // 10: role.RoleService.CreateRoleSystem:input_type -> role.CreateRoleSystemRequest
	4,  // 11: role.RoleService.GetRoleSystem:input_type -> role.GetRoleSystemRequest
	6,  // 12: role.RoleService.UpdateRoleSystem:input_type -> role.UpdateRoleSystemRequest
	8,  // 13: role.RoleService.DeleteRoleSystem:input_type -> role.DeleteRoleSystemRequest
	10, // 14: role.RoleService.ListRoleSystems:input_type -> role.ListRoleSystemsRequest
	3,  // 15: role.RoleService.CreateRoleSystem:output_type -> role.CreateRoleSystemResponse
	5,  // 16: role.RoleService.GetRoleSystem:output_type -> role.GetRoleSystemResponse
	7,  // 17: role.RoleService.UpdateRoleSystem:output_type -> role.UpdateRoleSystemResponse
	9,  // 18: role.RoleService.DeleteRoleSystem:output_type -> role.DeleteRoleSystemResponse
	11, // 19: role.RoleService.ListRoleSystems:output_type -> role.ListRoleSystemsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_role_role_proto_init() }
func file_proto_role_role_proto_init() {
	if File_proto_role_role_proto != nil {
		return
	}
	file_proto_role_role_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_role_proto_rawDesc), len(file_proto_role_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_role_role_proto_goTypes,
		DependencyIndexes: file_proto_role_role_proto_depIdxs,
		EnumInfos:         file_proto_role_role_proto_enumTypes,
		MessageInfos:      file_proto_role_role_proto_msgTypes,
	}.Build()
	File_proto_role_role_proto = out.File
	file_proto_role_role_proto_goTypes = nil
	file_proto_role_role_proto_depIdxs = nil
}
