// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/file/file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common "thaily/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStatus int32

const (
	FileStatus_FILE_PENDING FileStatus = 0
	FileStatus_APPROVED     FileStatus = 1
	FileStatus_REJECTED     FileStatus = 2
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_PENDING",
		1: "APPROVED",
		2: "REJECTED",
	}
	FileStatus_value = map[string]int32{
		"FILE_PENDING": 0,
		"APPROVED":     1,
		"REJECTED":     2,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_file_file_proto_enumTypes[0].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_proto_file_file_proto_enumTypes[0]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{0}
}

type TableType int32

const (
	TableType_TOPIC   TableType = 0
	TableType_MIDTERM TableType = 1
	TableType_FINAL   TableType = 2
	TableType_ORDER   TableType = 3
)

// Enum value maps for TableType.
var (
	TableType_name = map[int32]string{
		0: "TOPIC",
		1: "MIDTERM",
		2: "FINAL",
		3: "ORDER",
	}
	TableType_value = map[string]int32{
		"TOPIC":   0,
		"MIDTERM": 1,
		"FINAL":   2,
		"ORDER":   3,
	}
)

func (x TableType) Enum() *TableType {
	p := new(TableType)
	*p = x
	return p
}

func (x TableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_file_file_proto_enumTypes[1].Descriptor()
}

func (TableType) Type() protoreflect.EnumType {
	return &file_proto_file_file_proto_enumTypes[1]
}

func (x TableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableType.Descriptor instead.
func (TableType) EnumDescriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{1}
}

// ============= File =============
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Status        FileStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=file.FileStatus" json:"status,omitempty"`
	Table         TableType              `protobuf:"varint,5,opt,name=table,proto3,enum=file.TableType" json:"table,omitempty"`
	Option        string                 `protobuf:"bytes,6,opt,name=option,proto3" json:"option,omitempty"`
	TableId       string                 `protobuf:"bytes,7,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *File) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *File) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_PENDING
}

func (x *File) GetTable() TableType {
	if x != nil {
		return x.Table
	}
	return TableType_TOPIC
}

func (x *File) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *File) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *File) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *File) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *File) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Status        FileStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=file.FileStatus" json:"status,omitempty"`
	Table         TableType              `protobuf:"varint,4,opt,name=table,proto3,enum=file.TableType" json:"table,omitempty"`
	Option        string                 `protobuf:"bytes,5,opt,name=option,proto3" json:"option,omitempty"`
	TableId       string                 `protobuf:"bytes,6,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFileRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CreateFileRequest) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_PENDING
}

func (x *CreateFileRequest) GetTable() TableType {
	if x != nil {
		return x.Table
	}
	return TableType_TOPIC
}

func (x *CreateFileRequest) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *CreateFileRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *CreateFileRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_proto_file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	File          *string                `protobuf:"bytes,3,opt,name=file,proto3,oneof" json:"file,omitempty"`
	Status        *FileStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=file.FileStatus,oneof" json:"status,omitempty"`
	Table         *TableType             `protobuf:"varint,5,opt,name=table,proto3,enum=file.TableType,oneof" json:"table,omitempty"`
	Option        *string                `protobuf:"bytes,6,opt,name=option,proto3,oneof" json:"option,omitempty"`
	TableId       *string                `protobuf:"bytes,7,opt,name=table_id,json=tableId,proto3,oneof" json:"table_id,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFileRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateFileRequest) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

func (x *UpdateFileRequest) GetStatus() FileStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return FileStatus_FILE_PENDING
}

func (x *UpdateFileRequest) GetTable() TableType {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return TableType_TOPIC
}

func (x *UpdateFileRequest) GetOption() string {
	if x != nil && x.Option != nil {
		return *x.Option
	}
	return ""
}

func (x *UpdateFileRequest) GetTableId() string {
	if x != nil && x.TableId != nil {
		return *x.TableId
	}
	return ""
}

func (x *UpdateFileRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileResponse) Reset() {
	*x = UpdateFileResponse{}
	mi := &file_proto_file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileResponse) ProtoMessage() {}

func (x *UpdateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *common.SearchRequest  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilesRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFilesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_file_file_proto protoreflect.FileDescriptor

const file_proto_file_file_proto_rawDesc = "" +
	"\n" +
	"\x15proto/file/file.proto\x12\x04file\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xf8\x02\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.file.FileStatusR\x06status\x12%\n" +
	"\x05table\x18\x05 \x01(\x0e2\x0f.file.TableTypeR\x05table\x12\x16\n" +
	"\x06option\x18\x06 \x01(\tR\x06option\x12\x19\n" +
	"\btable_id\x18\a \x01(\tR\atableId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\tR\tupdatedBy\"\xe0\x01\n" +
	"\x11CreateFileRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.file.FileStatusR\x06status\x12%\n" +
	"\x05table\x18\x04 \x01(\x0e2\x0f.file.TableTypeR\x05table\x12\x16\n" +
	"\x06option\x18\x05 \x01(\tR\x06option\x12\x19\n" +
	"\btable_id\x18\x06 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"4\n" +
	"\x12CreateFileResponse\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetFileResponse\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\"\xce\x02\n" +
	"\x11UpdateFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04file\x18\x03 \x01(\tH\x01R\x04file\x88\x01\x01\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.file.FileStatusH\x02R\x06status\x88\x01\x01\x12*\n" +
	"\x05table\x18\x05 \x01(\x0e2\x0f.file.TableTypeH\x03R\x05table\x88\x01\x01\x12\x1b\n" +
	"\x06option\x18\x06 \x01(\tH\x04R\x06option\x88\x01\x01\x12\x1e\n" +
	"\btable_id\x18\a \x01(\tH\x05R\atableId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedByB\b\n" +
	"\x06_titleB\a\n" +
	"\x05_fileB\t\n" +
	"\a_statusB\b\n" +
	"\x06_tableB\t\n" +
	"\a_optionB\v\n" +
	"\t_table_id\"4\n" +
	"\x12UpdateFileResponse\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x10ListFilesRequest\x12-\n" +
	"\x06search\x18\x01 \x01(\v2\x15.common.SearchRequestR\x06search\"|\n" +
	"\x11ListFilesResponse\x12 \n" +
	"\x05files\x18\x01 \x03(\v2\n" +
	".file.FileR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*:\n" +
	"\n" +
	"FileStatus\x12\x10\n" +
	"\fFILE_PENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02*9\n" +
	"\tTableType\x12\t\n" +
	"\x05TOPIC\x10\x00\x12\v\n" +
	"\aMIDTERM\x10\x01\x12\t\n" +
	"\x05FINAL\x10\x02\x12\t\n" +
	"\x05ORDER\x10\x032\xc6\x02\n" +
	"\vFileService\x12?\n" +
	"\n" +
	"CreateFile\x12\x17.file.CreateFileRequest\x1a\x18.file.CreateFileResponse\x126\n" +
	"\aGetFile\x12\x14.file.GetFileRequest\x1a\x15.file.GetFileResponse\x12?\n" +
	"\n" +
	"UpdateFile\x12\x17.file.UpdateFileRequest\x1a\x18.file.UpdateFileResponse\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.file.DeleteFileRequest\x1a\x18.file.DeleteFileResponse\x12<\n" +
	"\tListFiles\x12\x16.file.ListFilesRequest\x1a\x17.file.ListFilesResponseB\bZ\x06./fileb\x06proto3"

var (
	file_proto_file_file_proto_rawDescOnce sync.Once
	file_proto_file_file_proto_rawDescData []byte
)

func file_proto_file_file_proto_rawDescGZIP() []byte {
	file_proto_file_file_proto_rawDescOnce.Do(func() {
		file_proto_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)))
	})
	return file_proto_file_file_proto_rawDescData
}

var file_proto_file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_file_file_proto_goTypes = []any{
	(FileStatus)(0),               // 0: file.FileStatus
	(TableType)(0),                // 1: file.TableType
	(*File)(nil),                  // 2: file.File
	(*CreateFileRequest)(nil),     // 3: file.CreateFileRequest
	(*CreateFileResponse)(nil),    // 4: file.CreateFileResponse
	(*GetFileRequest)(nil),        // 5: file.GetFileRequest
	(*GetFileResponse)(nil),       // 6: file.GetFileResponse
	(*UpdateFileRequest)(nil),     // 7: file.UpdateFileRequest
	(*UpdateFileResponse)(nil),    // 8: file.UpdateFileResponse
	(*DeleteFileRequest)(nil),     // 9: file.DeleteFileRequest
	(*DeleteFileResponse)(nil),    // 10: file.DeleteFileResponse
	(*ListFilesRequest)(nil),      // 11: file.ListFilesRequest
	(*ListFilesResponse)(nil),     // 12: file.ListFilesResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*common.SearchRequest)(nil),  // 14: common.SearchRequest
}
var file_proto_file_file_proto_depIdxs = []int32{
	0,  // 0: file.File.status:type_name -> file.FileStatus
	1,  // 1: file.File.table:type_name -> file.TableType
	13, // 2: file.File.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: file.File.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: file.CreateFileRequest.status:type_name -> file.FileStatus
	1,  // 5: file.CreateFileRequest.table:type_name -> file.TableType
	2,  // 6: file.CreateFileResponse.file:type_name -> file.File
	2,  // 7: file.GetFileResponse.file:type_name -> file.File
	0,  // 8: file.UpdateFileRequest.status:type_name -> file.FileStatus
	1,  // 9: file.UpdateFileRequest.table:type_name -> file.TableType
	2,  // 10: file.UpdateFileResponse.file:type_name -> file.File
	14, // 11: file.ListFilesRequest.search:type_name -> common.SearchRequest
	2,  // 12: file.ListFilesResponse.files:type_name -> file.File
	3,  // 13: file.FileService.CreateFile:input_type -> file.CreateFileRequest
	5,  // 14: file.FileService.GetFile:input_type -> file.GetFileRequest
	7,  // 15: file.FileService.UpdateFile:input_type -> file.UpdateFileRequest
	9,  // 16: file.FileService.DeleteFile:input_type -> file.DeleteFileRequest
	11, // 17: file.FileService.ListFiles:input_type -> file.ListFilesRequest
	4,  // 18: file.FileService.CreateFile:output_type -> file.CreateFileResponse
	6,  // 19: file.FileService.GetFile:output_type -> file.GetFileResponse
	8,  // 20: file.FileService.UpdateFile:output_type -> file.UpdateFileResponse
	10, // 21: file.FileService.DeleteFile:output_type -> file.DeleteFileResponse
	12, // 22: file.FileService.ListFiles:output_type -> file.ListFilesResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_file_file_proto_init() }
func file_proto_file_file_proto_init() {
	if File_proto_file_file_proto != nil {
		return
	}
	file_proto_file_file_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_file_proto_goTypes,
		DependencyIndexes: file_proto_file_file_proto_depIdxs,
		EnumInfos:         file_proto_file_file_proto_enumTypes,
		MessageInfos:      file_proto_file_file_proto_msgTypes,
	}.Build()
	File_proto_file_file_proto = out.File
	file_proto_file_file_proto_goTypes = nil
	file_proto_file_file_proto_depIdxs = nil
}
